#!/usr/bin/env node
/**
 * The content board, for Obsidian: every draft HERALD has made, grouped
 * by status, newest first, with its hook, source and file. Regenerated
 * after every run and every sync; generated: true, so never hand-edited.
 *
 *   npm run content:board
 */
import fs from 'node:fs';
import path from 'node:path';
import { brainDir, parseFrontmatter, serializeFrontmatter, writeGenerated, stamp } from './lib/brain.mjs';

const brain = brainDir();
const STATUSES = ['draft', 'review', 'approved', 'scheduled', 'posted', 'killed'];
const drafts = [];
for (const folder of ['Drafts', 'Approved', 'Posted', 'Killed']) {
  const dir = path.join(brain, '02-Content', folder); if (!fs.existsSync(dir)) continue;
  for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.md'))) {
    const { data } = parseFrontmatter(fs.readFileSync(path.join(dir, f), 'utf8'));
    if (data?.type === 'content-draft') drafts.push({ ...data, file: f.replace(/\.md$/, ''), folder });
  }
}
drafts.sort((a, b) => String(b.created).localeCompare(String(a.created)));
const by = Object.fromEntries(STATUSES.map((s) => [s, drafts.filter((d) => d.status === s)]));
const sources = fs.existsSync(path.join(brain, '02-Content', 'Sources')) ? fs.readdirSync(path.join(brain, '02-Content', 'Sources')).filter((f) => f.endsWith('.md')).length : 0;
const row = (d) => `| [[${d.file}\\|${d.id}]] | ${d.format} | ${d.platform} | ${String(d.hook).replace(/\|/g, '\\|')} | ${d.source_note || d.source_module} | ${d.created} |`;
const md = serializeFrontmatter({ type: 'board', created: stamp(), updated: stamp(), status: 'active', agent: 'HERALD', generated: true, tags: ['content', 'board'] }) + `# Content Board

${drafts.length} drafts · ${STATUSES.map((s) => `${by[s].length} ${s}`).join(' · ')} · ${sources} source notes copied.

Only a human moves a draft's \`status\`; HERALD only ever writes \`draft\`.
Move it in the file's frontmatter here in Obsidian, or on the site (BEACON or
the CONTENT view) — \`npm run vault:sync\` brings the site's changes into
these files. Regenerated by \`npm run content:board\`.

${STATUSES.map((s) => `## ${s.charAt(0).toUpperCase() + s.slice(1)} (${by[s].length})

${by[s].length ? `| Draft | Format | Platform | Hook | Source | Created |\n| --- | --- | --- | --- | --- | --- |\n${by[s].map(row).join('\n')}` : '_none_'}
`).join('\n')}`;
const status = writeGenerated(path.join(brain, '02-Content', 'Board.md'), md, { write: true });
console.log(`✓ content board → brain/02-Content/Board.md (${status}) — ${drafts.length} drafts`);
